fix: experimental refactor canary build

diff --git a/.github/workflows/cd-canary.yml b/.github/workflows/cd-canary.yml
--- a/.github/workflows/cd-canary.yml
+++ b/.github/workflows/cd-canary.yml
@@ -18,11 +18,7 @@ jobs:
         with:
           ssh-private-key: ${{ secrets.CANARY_DEPLOY }}
 
-      - name: Build Canary
-        run: |
-          bash ./gobuild.sh
-
-      - name: Release Canary Build
+      - name: Setup Git
         env:
           USE_SSH: true
           GIT_USER: ${{ secrets.GH_USER }}
@@ -31,12 +27,23 @@ jobs:
           git config --global user.email '${{ secrets.GH_EMAIL }}'
           git config --global user.name '${{ secrets.GH_USER }}'
 
+          git rm -rf . || echo "unable to rm -rf ."
+
+      - name: Build Canary
+        run: |
+          bash ./gobuild.sh
+
+      - name: Release Canary Build
+        env:
+          USE_SSH: true
+          GIT_USER: ${{ secrets.GH_USER }}
+        run: |
           git checkout origin/canary-builds
           git checkout -b canary-builds
           git branch --set-upstream-to=origin/canary-builds
-          git rm -rf . || echo "unable to rm -rf ."
 
           cd ./build
+          git rm -rf . || echo "unable to rm -rf ."
           git add --all
 
           git commit -m "Deploy canary - based on ${{ github.sha }}"
